# Extracting data to different formats

In this notebook, we will look at how we can export data from a NetCDF file into different formats. This will include:
* Exporting data to a numpy array
* Exporting data to a Pandas dataframe that we can write to a CSV or XLSX file

Let's first revist this example from part 01, importing a depth profile


In [12]:
import xarray as xr
netcdf_file = 'https://opendap1.nodc.no/opendap/physics/point/cruise/nansen_legacy-single_profile/NMDC_Nansen-Legacy_PR_CT_58US_2021708/CTD_station_P1_NLEG01-1_-_Nansen_Legacy_Cruise_-_2021_Joint_Cruise_2-1.nc'
xrds = xr.open_dataset(netcdf_file)
xrds

<xarray.Dataset>
Dimensions:        (PRES: 320)
Coordinates:
  * PRES           (PRES) float32 1.0 2.0 3.0 4.0 ... 317.0 318.0 319.0 320.0
Data variables: (12/33)
    PRES_QC        (PRES) float32 ...
    TEMP           (PRES) float32 ...
    PSAL           (PRES) float32 ...
    FLU2           (PRES) float32 ...
    CNDC           (PRES) float32 ...
    DENS           (PRES) float32 ...
    ...             ...
    OXYOCPVL-1_QC  (PRES) float32 ...
    SPAR_QC        (PRES) float32 ...
    PAR_QC         (PRES) float32 ...
    PSAL-2_QC      (PRES) float32 ...
    TEMP-2_QC      (PRES) float32 ...
    ATTNZS01_QC    (PRES) float32 ...
Attributes: (12/73)
    qc_manual:                       Recommendations for in-situ data Near Re...
    contact:                         datahjelp@hi.no
    distribution_statement:          These data are public and free of charge...
    naming_authority:                no.unis
    license:                         https://creativecommons.org/licenses/by/...
    data_assembly_center:            IMR
    ...                              ...
    station_name:                    P1 (NLEG01)
    _NCProperties:                   version=2,netcdf=4.6.3,hdf5=1.10.5
    date_created:                    2022-08-08T12:44:34Z
    doi:                             10.21335/NMDC-2085836005-P1_NLEG01-1
    title:                           CTD_station_P1_NLEG01-1_-_Nansen_Legacy_...
    metadata_link:                   https://doi.org/10.21335/NMDC-2085836005...

## Variable with 1 dimension to numpy array

By default when we access the data from a variable, the values are extracted as a NumPy array. Note that we have not needed to import numpy to do this.

In [14]:
myarray = xrds['TEMP'].values
myarray

array([3.735, 3.738, 3.739, 3.741, 3.736, 3.737, 3.736, 3.742, 3.736,
       3.738, 3.783, 3.833, 3.838, 3.837, 3.83 , 3.806, 3.792, 3.79 ,
       3.814, 3.846, 3.858, 3.833, 3.815, 3.817, 3.814, 3.812, 3.792,
       3.709, 3.704, 3.642, 3.582, 3.546, 3.512, 3.484, 3.368, 3.297,
       3.165, 3.106, 3.094, 3.094, 3.102, 3.079, 3.094, 3.076, 3.035,
       3.009, 2.992, 2.981, 2.954, 2.933, 2.903, 2.874, 2.85 , 2.824,
       2.801, 2.787, 2.764, 2.713, 2.711, 2.705, 2.701, 2.696, 2.682,
       2.665, 2.651, 2.647, 2.642, 2.635, 2.624, 2.588, 2.604, 2.608,
       2.593, 2.507, 2.472, 2.468, 2.46 , 2.453, 2.441, 2.43 , 2.431,
       2.43 , 2.431, 2.433, 2.43 , 2.417, 2.394, 2.382, 2.361, 2.335,
       2.32 , 2.303, 2.275, 2.267, 2.263, 2.277, 2.27 , 2.265, 2.262,
       2.256, 2.241, 2.216, 2.201, 2.191, 2.176, 2.135, 2.11 , 2.091,
       2.071, 2.064, 2.103, 2.106, 2.099, 2.095, 2.092, 2.088, 2.082,
       2.085, 2.093, 2.09 , 2.089, 2.085, 2.054, 2.022, 2.019, 2.021,
       2.026, 2.027,

In [15]:
type(myarray)

numpy.ndarray

## Variables with 1 dimension to pandas dataframe

Alternatively, you might want to export the data into a pandas dataframe. Dataframes are essentially tables of data and you can export them easily to CSV or XLSX files.

In [16]:
xrds['TEMP'].to_dataframe()

TEMP
PRES        
1.0    3.735
2.0    3.738
3.0    3.739
4.0    3.741
5.0    3.736
...      ...
316.0  1.287
317.0  1.287
318.0  1.287
319.0  1.287
320.0  1.287

[320 rows x 1 columns]

See how the relevant coordinate variable has been extracted along with it as the index to the dataframe?

Now let's try several variables together.

In [17]:
xrds[['TEMP', 'PSAL', 'DENS', 'SVEL']].to_dataframe()

TEMP       PSAL       DENS         SVEL
PRES                                           
1.0    3.735  34.254002  27.207001  1464.550049
2.0    3.738  34.259998  27.209999  1464.579956
3.0    3.739  34.261002  27.211000  1464.599976
4.0    3.741  34.266998  27.216000  1464.630005
5.0    3.736  34.258999  27.209999  1464.619995
...      ...        ...        ...          ...
316.0  1.287  34.916000  27.945000  1459.969971
317.0  1.287  34.916000  27.945000  1459.989990
318.0  1.287  34.916000  27.945000  1460.010010
319.0  1.287  34.916000  27.945000  1460.020020
320.0  1.287  34.916000  27.945000  1460.040039

[320 rows x 4 columns]

## Data with more dimensions

What about these CTD data that are published cruise by cruise?

In [19]:
xrds = xr.open_dataset('https://opendap1.nodc.no/opendap/physics/point/cruise/nansen_legacy/NMDC_Nansen-Legacy_PR_CT_58US_2022702.nc')
xrds

<xarray.Dataset>
Dimensions:        (TIME: 29, LATITUDE: 29, LONGITUDE: 29, POSITION: 29,
                    DEPTH: 3555)
Coordinates:
  * TIME           (TIME) datetime64[ns] 2022-02-22T17:47:32 ... 2022-03-11T1...
  * LATITUDE       (LATITUDE) float32 76.0 80.68 80.6 ... 80.39 79.14 78.34
  * LONGITUDE      (LONGITUDE) float32 31.22 33.81 33.56 ... 29.77 8.917 14.47
Dimensions without coordinates: POSITION, DEPTH
Data variables: (12/37)
    POSITION_QC    (POSITION) float32 ...
    DIRECTION      object ...
    PRES           (TIME, DEPTH) float32 ...
    PRES_QC        (TIME, DEPTH) float32 ...
    TEMP           (TIME, DEPTH) float64 ...
    PSAL           (TIME, DEPTH) float64 ...
    ...             ...
    SPAR_QC        (TIME, DEPTH) float32 ...
    PAR_QC         (TIME, DEPTH) float32 ...
    PSAL-2_QC      (TIME, DEPTH) float32 ...
    TEMP-2_QC      (TIME, DEPTH) float32 ...
    ATTNZS01_QC    (TIME, DEPTH) float32 ...
    TIME_QC        (TIME) float32 ...
Attributes: (12/67)
    _NCProperties:                  version=2,netcdf=4.7.4,hdf5=1.12.0,
    qc_manual:                      Recommendations for in-situ data Near Rea...
    contact:                        datahjelp@hi.no
    distribution_statement:         These data are public and free of charge....
    naming_authority:               Norwegian Marine Datacenter
    license:                        https://creativecommons.org/licenses/by/4...
    ...                             ...
    creator_name:                   Angelika Renner
    creator_type:                   person
    creator_email:                  angelika.renner@hi.no
    creator_url:                    https://www.hi.no/hi
    publisher:                      The Norwegian Marine Data Centre (NMD)
    publisher_url:                  https://www.nmdc.no/

The file contains many depth profiles. Therefore, most of the data variables have two dimensions; time and depth.

You might notice that there is no depth coordinate variable. Why not? The depth profiles are binned into 1 dbar bins. The density of sea water is a function of sea water and salinity, and so is not constant. So you can't use a single depth variable for all the profiles. 

They could have included pressure as a coordinate variable.

They could have also published all the depth profiles in separate files. Then each file could include its own depth coordinate variable. It is good practice to publish data with finer granularity because each file can be simpler and thus easier to create, understand, and build services upon. Granularity of data and working with multiple NetCDF files will be focus of a later tutorial. 

In [21]:
xrds['TEMP'].values

array([[ 2.044,  2.033,  1.99 , ...,    nan,    nan,    nan],
       [11.774, 11.076,  2.619, ...,    nan,    nan,    nan],
       [10.136,  8.028,  3.194, ...,    nan,    nan,    nan],
       ...,
       [ 0.113, -0.065,  0.325, ...,    nan,    nan,    nan],
       [ 3.382,  2.91 ,  2.969, ...,    nan,    nan,    nan],
       [-0.931, -1.644, -1.522, ...,    nan,    nan,    nan]])

What if we wanted to access one specific depth profile. How would we do that? 

We can start by accessing only the 5th depth profile.

In [24]:
profile5 = xrds['TEMP'][5].values
print(profile5)
print('time: ',xrds['TIME'][5].values)
print('latitude: ',xrds['LATITUDE'][5].values)
print('longitude: ',xrds['LONGITUDE'][5].values)

[-2.403  3.934 12.479 ...    nan    nan    nan]
time:  2022-03-01T20:43:21.000000000
latitude:  82.0375
longitude:  29.7788


However, often we won't know which number the profile is. It might be quicker to extract the depth profile collected at a certain time, for example. Maybe we don't know the exact time, let's find the profile closest to the time we are interested in.

In [82]:
import numpy as np
timestamp = np.datetime64(dt.datetime(2022, 3, 5, 11)) 
timestamp

numpy.datetime64('2022-03-05T11:00:00.000000')

Now we need to save the time variable to a numpy array.

In [83]:
time_var = xrds['TIME'].values
time_var

array(['2022-02-22T17:47:32.000000000', '2022-02-27T14:16:11.000000000',
       '2022-02-28T08:09:41.000000000', '2022-02-28T15:28:53.999999744',
       '2022-03-01T06:29:59.000000000', '2022-03-01T20:43:21.000000000',
       '2022-03-03T02:25:48.000000000', '2022-03-04T05:00:09.000000000',
       '2022-03-04T12:17:37.000000000', '2022-03-04T19:00:02.000000000',
       '2022-03-05T00:13:21.000000000', '2022-03-05T10:49:14.000000000',
       '2022-03-05T13:27:56.000000000', '2022-03-05T21:34:34.000000256',
       '2022-03-05T23:36:33.000000000', '2022-03-06T01:14:25.000000000',
       '2022-03-06T02:06:18.000000000', '2022-03-06T03:06:23.000000000',
       '2022-03-06T04:22:53.000000256', '2022-03-06T17:52:05.000000000',
       '2022-03-06T18:43:00.000000000', '2022-03-06T20:22:08.000000000',
       '2022-03-06T21:33:10.000000000', '2022-03-06T23:02:54.000000000',
       '2022-03-07T00:08:03.000000000', '2022-03-07T01:26:13.000000000',
       '2022-03-08T07:49:24.000000000', '2022-03-10

Calculate the difference between each element in the time coordinate variable and the specific timestamp

In [86]:
import numpy as np
time_diff = np.abs(time_var - timestamp)
time_diff

array([925948000000000, 506629000000000, 442219000000000, 415866000000256,
       361801000000000, 310599000000000, 203652000000000, 107991000000000,
        81743000000000,  57598000000000,  38799000000000,    646000000000,
         8876000000000,  38074000000256,  45393000000000,  51265000000000,
        54378000000000,  57983000000000,  62573000000256, 111125000000000,
       114180000000000, 120128000000000, 124390000000000, 129774000000000,
       133683000000000, 138373000000000, 247764000000000, 402920000000000,
       544723000000000], dtype='timedelta64[ns]')

Find the index of the element with the smallest difference (nearest timestamp)

In [89]:
nearest_index = int(time_diff.argmin().item())
nearest_index

11

In [91]:
xrds['TEMP'][nearest_index].values

array([-1.68 , -1.666, -1.661, ...,    nan,    nan,    nan])

Now let's instead export multiple variables and multiple depth profiles to a single pandas dataframe.

In [94]:
df = xrds[['TEMP','PSAL', 'PRES', 'SVEL']].to_dataframe()
df

# df.to_excel('/your/filepath/ctd_data.xlsx')
# df.to_csv('/your/filepath/ctd_data.csv')

TEMP    PSAL  PRES     SVEL
TIME                DEPTH                              
2022-02-22 17:47:32 0      2.044  34.953   5.0  1458.29
                    1      2.033  34.953   6.0  1458.25
                    2      1.990  34.955   7.0  1458.08
                    3      2.007  34.954   8.0  1458.17
                    4      1.987  34.954   9.0  1458.10
...                          ...     ...   ...      ...
2022-03-11 18:18:43 3550     NaN     NaN   NaN      NaN
                    3551     NaN     NaN   NaN      NaN
                    3552     NaN     NaN   NaN      NaN
                    3553     NaN     NaN   NaN      NaN
                    3554     NaN     NaN   NaN      NaN

[103095 rows x 4 columns]

Notice that in this case both coordinate variables are plotted as individual columns. The data variables are also long columns of data. 